### ISSUE TITLE
Analysis: GWAS: ALL

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#10]
- [x] add function to FinngenUtils to run gwas
- [ ] add function to HadesExtras to compare endpoints
- [x] add menu to CohortOperation2

**Comment by anastasia-shch** [comment]
@javier-gracia-tabuenca-tuni What does this item require "**add function to HadesExtras to compare endpoints**" ?

**Comment by anastasia-shch** [comment]
@javier-gracia-tabuenca-tuni can this be closed? I can see that there is still this item in the list "**add function to HadesExtras to compare endpoints**" unchecked

**Comment by anastasia-shch** [comment]
Should I implement it?
