### ISSUE TITLE
library with genotiped finngen ids and others

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#133]
New libraries in CO2 – these would be really good for task forces
genetic outliers (non-Finns in PCA) (Mitja/Arto would know where to find the list of these)
individuals with chip genotyping (~433K - available from Timo)
individuals with exome sequencing (Mitja "pulled from exome file and copied here  library-red/wes_gnomad_v4_min_QC/ ")
individuals with Olink data
individuals in EA studies?

**Comment by mpreeve** [comment]
genetic outliers (non-Finns in PCA) (Mitja/Arto would know where to find the list of these)
      - genetic outliers (individuals not in covariate file and not used in GWAS)
      - OUTLIERS
individuals with chip genotyping (~433K - available from Timo)
      - FinnGen Affy chip genotyped (people not in this group may come from legacy genotyping methods)
      - CHIP
individuals with exome sequencing (Mitja "pulled from exome file and copied here library-red/wes_gnomad_v4_min_QC/ ")
      - individuals with exome sequencing
      - WES
individuals with Olink data (Rodos & Elisa would know who these are)
       - individuals with Olink proteomics data 
       - PROTEOMICS
individuals in EA studies? (Elisa)
      - individuals with extra data from Expansion Area studies
      -EA

**Comment by shanmukhasampath** [comment]
individuals with Olink data (Rodos & Elisa would know who these are) 
- individuals with Olink proteomics data
- PROTEOMICS
- **EA5 olink library-red folder** for batch 1-3. (**THESE ARE HEALTHY. FURTHER TESTING**)
- For next batch (Check email) 2200 will be coming which are in taskforces IBD, Kidney and others.

individuals in EA studies? (Elisa)

**Comment by javier-gracia-tabuenca-tuni** [comment]
DETAILS
- the names of the cohorts in cohortDescription table must include the text '[CohortLibrary]'
- The start and end dates in the cohort table are taken from the observation table start of observation and end of observation
- in addition to the above cohorts, we need  the following cohorts
    - "ALL [CohortLibrary]": All the finngen ids
    - "MALE [CohortLibrary]": Male finngen ids
    - "FEMALE [CohortLibrary]": Female finngen ids

**Comment by shanmukhasampath** [comment]
For details of this issue. Please do check this issue in AtlasDevelopment git repo
https://github.com/FINNGEN/AtlasDevelopment/issues/66
