### ISSUE TITLE
mod_formTimeWindow to return non overlaping windows

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#17]
https://github.com/FINNGEN/CohortOperations2/blob/development/R/mod_FormTimeWindows.R

Should return non overlapping windows 

NOW: if 6 scrolls in the bar are set for example to -200, -100 , 0 , 0, 100, 200
  it makes windows [-200, -100], [-100, 0], [0,0], [0, 100] and [100, 200] 
i this way day -100, day 0, and day 100 are in more than one window, and therefore the events on these windows will be repeated

It should be [-200, -101], [-100, -1], [0,0], [1, 100] and [101, 200]

**Comment by javier-gracia-tabuenca-tuni** [comment]
for example



![Image](https://github.com/FINNGEN/CohortOperations2/assets/54809193/772215d0-ff9b-4ac4-8624-e7c7c1a14b17)

here all 3 windows have a 100% cases with  the same code bcs is the code used to define the cohort start date and therefore
it appears in day 0 for all cases

**Comment by siirtola** [comment]
The just uploaded version does not return overlapping windows.

**Comment by javier-gracia-tabuenca-tuni** [comment]
closed by #18
