### ISSUE TITLE
Analysis: timeCodeWAS: unable to select small windows

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#2]
![Image](https://github.com/FINNGEN/CohortOperations2/assets/54809193/4b301f58-e11b-481a-9ea6-e5c3d6e36ea2)

very hard to select window between 0 And 0 days 
some time impossible 
hard to fine tune the days to get the years, sometimes impossible  

with impossible, i mean that if the bar has many values and is short, some time the scroll dont find all the numeric values 

https://github.com/FINNGEN/CohortOperations2/blob/ecfdb16a8f3ee163c00a3e6572368449f9ce33f4/R/mod_FormTimeWindows.R#L3

**Comment by siirtola** [comment]
Apparently you haven't noticed that you can move the controls with arrow keys? The last slider touched will move left and right with them. I don't understand the "select window between 0 and 0 days".

**Comment by javier-gracia-tabuenca-tuni** [comment]
ah good
No, i haven't notice this, so I guess other will not notice either, 
the is has to be somehow explain 
 
a window from 0 to 0 should appear as default
we always want to separate the events on the onset day

**Comment by siirtola** [comment]
The codeWAS computation does not understand the "0 to 0" window. 
With the input
![image](https://github.com/FINNGEN/CohortOperations2/assets/7419735/443a032c-56d1-43ff-a898-e11668b1c021)
the windows will be
![image](https://github.com/FINNGEN/CohortOperations2/assets/7419735/3a8e635f-0d73-439a-913f-f43a9b9ee04e)

**Comment by javier-gracia-tabuenca-tuni** [comment]
ok, i will investigate, may be something wrong with in the app calling the code runner, 
bcs with code i can run a 0 to  o window
