### ISSUE TITLE
import from file: error when trying to load a file dowloaded from cohort operations 1

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#23]
<img width="412" alt="Screenshot 2024-02-29 at 12 57 52" src="https://github.com/FINNGEN/CohortOperations2/assets/54809193/878593f0-3733-41cb-a201-ea279bf22de4">

i download a file from co1, which has columns  as in cohortData formt

but tells me that the column is not in dataformat

**Comment by javier-gracia-tabuenca-tuni** [comment]
if i rename the columns of the same file, it works

**Comment by siirtola** [comment]
Please provide a data file reproduce the problem

**Comment by javier-gracia-tabuenca-tuni** [comment]
[cohortData_asthma_eunomia_enddate_na_but_one.csv](https://github.com/FINNGEN/CohortOperations2/files/14458337/cohortData_asthma_eunomia_enddate_na_but_one.csv)

i think the error comes from readr::read_csv trying to guess the column type 
it try to guess the column type form the first /or last 1000 rows
if these are na then it thinks is a logical

**Comment by javier-gracia-tabuenca-tuni** [comment]
easy fix could be to set the guess_max to millions
but that may not be reasonable
may make things very slow

**Comment by siirtola** [comment]
What if I force the column types based on the assignments? I'll try if that works

**Comment by javier-gracia-tabuenca-tuni** [comment]
closed by #26
