### ISSUE TITLE
Operate cohorts UI

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#31]
this is similar to 
https://github.com/FINNGEN/CohortOperations2/blob/development/R/mod_MatchCohorts.R

This file can be copied to a new file mod_OperateCohorts.R
the modify it by removing 
Cohorts and Settings sections 
Create a Settings section with a drag and drop similar to 
https://github.com/FINNGEN/CohortOperationsShinyApp/blob/b4cff35787d6deb823f893f37f71d8687b6da3a2/R/mod_operate_cohorts.R#L79

Where the element to drag are 
- the sort names in the cohort table
- (
- )
- Upd
- Ip
- Mp

the area with the draged elements outputs a string with the elements on it

**Comment by javier-gracia-tabuenca-tuni** [comment]
It may be easier to make a module for the drag and drop 
inputs, list of cohort names
output the resulting string

**Comment by siirtola** [comment]
There is now a module `mod_DragAndDrop` just to build the operation expression in branch `drag-and-drop-ui`.
