### ISSUE TITLE
Display of names in cohorts export

### ISSUE THREAD

**Issue by siirtola** [FINNGEN/CohortOperations2#75]
Could we have it display as:

alias (long cohort name) 

rather than

alias -- long cohort name

my concern is that the long dash looks like a minus mathematical sign 

![Image](https://github.com/user-attachments/assets/aafa6b07-3412-4441-9a9c-f40c0ddcc242)

**Comment by javier-gracia-tabuenca-tuni** [comment]
is not a - is some emoji https://emojipedia.org/minus

the string is parsed at some point to separate alias from long name, 
that was the easiest way, if () or other characters, appear in the long name, make it harder to make this separation 
eg
allias (long name with (brakets))

not impossible to do, but i chose the fastest solution at that point

**Comment by siirtola** [comment]
OK, I made the change, but didn't spot the parsing problem! Luckily, I didn't send the pr yet.

**Comment by javier-gracia-tabuenca-tuni** [comment]
ok,  I remembered wrong, this change does not break the code. 
you can make it, 
but has to happen in all the places not only in the export

It is more that, i was thinking that may be confusing to use () if these are used in the name

**Comment by siirtola** [comment]
Yes, that would be really confusing. Could we prevent using some letter in the name? Like colon or semicolon? 

`shortname : longname`
