### ISSUE TITLE
Import: From Atlas/Library, slow, copy if it has been ran, as to ran in Atlas

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#77]
Loading a FinnGen list from a file also seems slow

**Comment by javier-gracia-tabuenca-tuni** [comment]
NOTES
 
here is where co2 ask Atlas for the SQL to build the cohort 
https://github.com/FINNGEN/CohortOperations2/blob/0bd4f26972eabc50be166971992ba0d9cde1ccec/R/mod_ImportCohortsFromAtlas.R#L122C1-L126C1

this should be replace with 
- asking Atlas if the cohorts selected to import have been generated and up to date/generated but outdated/not generated.
 This can be done with some function in the ROhdsiWebApi package. 
- If generated but outdated OR not generated, inform the user that they will be generated and will take some mins
- When generated and up to date, replace the SQL that build the cohort with one that copies them similar to how it is done when copying the endpoints https://github.com/FINNGEN/CohortOperations2/blob/0bd4f26972eabc50be166971992ba0d9cde1ccec/R/mod_ImportCohortsFromCohortTable.R#L135

Test, and build unit test for this in AtlasDevelopment

**Comment by anastasia-shch** [comment]
@javier-gracia-tabuenca-tuni what is the criteria for telling whether the cohort is outdated or not?
