### ISSUE TITLE
Notes from MP

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#79]
- CodeWas table download https://finngencommunity.slack.com/archives/G01DD70LTCN/p1724431447539259
- Analysis tables, better filtering, and shorting. Numbers are converted to strings making sorting wrong 
https://finngencommunity.slack.com/archives/G01DD70LTCN/p1724381565190599

**Comment by siirtola** [comment]
These notes are now here:

- https://finngencommunity.slack.com/archives/C02G115UNJE/p1724381520517749
