### ISSUE TITLE
CO2 v1.0.0 first issues 

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperations2#99]
We can use this to write the issues for the first testing in sandbox 17 Sep:

- Loading from atlas slows down the start up, can we do something ? (enhancement)
- Operate cohorts: error in upset plot when only one cohort selected (check again may be fixed)
- Operate Cohorts: move 'New Name' over the upset plot, so it is visible (enhacement)
- Cohort Demographics View: plot has cohort ids instead of cohort names (old)
- Cohort Operations: names in columns in tables not matching cohort table ()
- CodeWAS View: cohort table to chow case controls ()

**Comment by siirtola** [comment]
The CO2Modules is not up-to-date in sandbox – it makes it hard to figure out what's wrong.
The manual testing  in RStudio is broken and fails to run.

**Comment by javier-gracia-tabuenca-tuni** [comment]
sorry, nothing is yet on sandbox
these are some temporal notes i took
i didnt ask you to act on these

**Comment by siirtola** [comment]
OK, no problem.

**Comment by javier-gracia-tabuenca-tuni** [comment]
personal notes, do not act 

- error in creating tables, solve, '-' not valid in a bq name
- naming ??
<img width="359" alt="image" src="https://github.com/user-attachments/assets/fa43ecee-d681-40d9-88d6-4802b1ad2184">
- cohort overlaps settings 
<img width="400" alt="image" src="https://github.com/user-attachments/assets/0b26f880-609f-4a20-a034-28cec367e209">
- cohort demographics viewer, plot, should be short name instead of full name ?
<img width="219" alt="image" src="https://github.com/user-attachments/assets/45b49847-9ee1-46de-a947-37b36d7dc677">
- short name missing from all the cohort pickers in all the analysis 
- in codeWAS warning for already matched cohots ?
- 
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/8ef64e32-db81-4ce8-a44e-c3bbdf2ddeb5">

**Comment by anastasia-shch** [comment]
Related to "Names in the database picker (bug) ??" - yes it appears there is a typo in the sb configs in the docker. I will fix this tomorrow in the repo and docker.
